/**
 * Copyright (C) 2024 Mailvelope GmbH
 * Licensed under the GNU Affero General Public License version 3
 */
/**
 * date-fns helper functions
 */
// import locales generated by grunt:date-fns-locales task
import locales from '../../tmp/gen/date-fns-locales';

/**
 * Loads locale from `date-fns`
 * @param {string} language - language string to load from `date-fns`
 * @returns {import('date-fns').Locale} `date-fns/Locale` object
 */
export function getLocale(language) {
  return locales[language];
}
