# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1393179692);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1393178521);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1393179572);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.safebrowsing.provider.0.gethashURL", "http://localhost/safebrowsing-dummy/gethash");
user_pref("browser.safebrowsing.provider.0.keyURL", "http://localhost/safebrowsing-dummy/newkey");
user_pref("browser.safebrowsing.provider.0.updateURL", "http://localhost/safebrowsing-dummy/update");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "2014012800");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.buildID", "2014012800");
user_pref("browser.startup.homepage_override.mstone", "27.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":4}");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.warnOnQuit", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1393264157720");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1393177757719");
user_pref("datareporting.sessions.current.activeTicks", 5);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1142);
user_pref("datareporting.sessions.current.main", 41);
user_pref("datareporting.sessions.current.sessionRestored", 1262);
user_pref("datareporting.sessions.current.startTime", "1393179859797");
user_pref("datareporting.sessions.current.totalTime", 22);
user_pref("datareporting.sessions.currentIndex", 9);
user_pref("datareporting.sessions.previous.0", "{\"s\":1393177757375,\"a\":12,\"t\":64,\"c\":true,\"m\":40,\"fp\":1605,\"sr\":1864}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1393177840415,\"a\":7,\"t\":36,\"c\":true,\"m\":41,\"fp\":1198,\"sr\":1312}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1393178273037,\"a\":5,\"t\":26,\"c\":true,\"m\":41,\"fp\":1073,\"sr\":1178}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1393178303920,\"a\":18,\"t\":87,\"c\":true,\"m\":30,\"fp\":1191,\"sr\":1306}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1393178400173,\"a\":31,\"t\":220,\"c\":true,\"m\":41,\"fp\":1266,\"sr\":1390}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1393178626487,\"a\":6,\"t\":26,\"c\":false,\"m\":40,\"fp\":1140,\"sr\":1256}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1393179180936,\"a\":7,\"t\":31,\"c\":false,\"m\":41,\"fp\":1093,\"sr\":1206}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1393179311558,\"a\":6,\"t\":26,\"c\":false,\"m\":41,\"fp\":1132,\"sr\":1281}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1393179451557,\"a\":26,\"t\":246,\"c\":true,\"m\":41,\"fp\":1386,\"sr\":1497}");
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.errorconsole.enabled", true);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_BROWSERCONSOLE_OPENED_PER_USER_FLAG\":\"27.0\"}");
user_pref("devtools.toolsidebar-width.webconsole", 300);
user_pref("distribution.openSUSE.bookmarksProcessed", true);
user_pref("extensions.autoDisableScopes", 10);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.blocklist.url", "http://localhost/extensions-dummy/blocklistURL");
user_pref("extensions.bootstrappedAddons", "{\"jid1-PPxXH40gbJawnA@jetpack\":{\"version\":\"0.7.0\",\"type\":\"extension\",\"descriptor\":\"/home/jb/code/mailvelope/spec/ff_testprofile/extensions/jid1-PPxXH40gbJawnA@jetpack.xpi\"}}");
user_pref("extensions.checkCompatibility.27.0", false);
user_pref("extensions.checkCompatibility.nightly", false);
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:27.0");
user_pref("extensions.enabledScopes", 5);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1392069197000,\"rdfTime\":1391677174000}}},{\"name\":\"app-profile\",\"addons\":{\"jid1-PPxXH40gbJawnA@jetpack\":{\"descriptor\":\"/home/jb/code/mailvelope/spec/ff_testprofile/extensions/jid1-PPxXH40gbJawnA@jetpack.xpi\",\"mtime\":1393179859000}}}]");
user_pref("extensions.installDistroAddons", false);
user_pref("extensions.lastAppVersion", "27.0");
user_pref("extensions.lastPlatformVersion", "27.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.sdk.console.logLevel", "info");
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.update.url", "http://localhost/extensions-dummy/updateURL");
user_pref("extensions.webservice.discoverURL", "http://localhost/extensions-dummy/discoveryURL");
user_pref("gecko.buildID", "2014012800");
user_pref("gecko.mstone", "27.0");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("javascript.options.strict", true);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 101144);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("toolkit.startup.last_success", 1393179859);
user_pref("toolkit.telemetry.previousBuildID", "2014012800");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1395769760);
user_pref("urlclassifier.updateinterval", 172800);
